openapi: 3.0.0
info:
  title: Blockchain Transcript Management API
  version: 1.0.0
  description: A blockchain-based transcript management system API.
servers:
  - url: http://localhost:5000/api
    description: Local server

paths:
  /admin/login:
    post:
      summary: Admin login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  
                  example: admin@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: jwt_token_here
                  admin:
                    $ref: '#/components/schemas/Admin'
        '400':
          description: Bad request

  /admin/student:
    post:
      summary: Create a new student
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Bad request

  /admin/student/{student_id}:
    put:
      summary: Update student details
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: student_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Bad request

  /admin/student/{student_id}/send-password:
    post:
      summary: Send default password to student
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: student_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Password sent successfully
        '400':
          description: Bad request

  /admin/student/{student_id}/transcript:
    post:
      summary: Generate transcript details
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: student_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transcript'
      responses:
        '201':
          description: Transcript generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transcript'
        '400':
          description: Bad request

  /admin/student/{student_id}/transcript/{transcript_id}/block:
    post:
      summary: Create blockchain-based shareable transcript details
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: student_id
          required: true
          schema:
            type: string
        - in: path
          name: transcript_id
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Block details created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcriptId:
                    type: string
                    example: transcript_id_here
                  blockDetails:
                    type: string
                    example: block_details_here
        '400':
          description: Bad request

  /student/login:
    post:
      summary: Student login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: student@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: jwt_token_here
                  student:
                    $ref: '#/components/schemas/Student'
        '400':
          description: Bad request

  /student/{student_id}:
    put:
      summary: Update student details
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: student_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Bad request

  /student/{student_id}/transcript/{transcript_id}/shareable:
    get:
      summary: Retrieve shareable transcript
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: student_id
          required: true
          schema:
            type: string
        - in: path
          name: transcript_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Shareable transcript retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcriptId:
                    type: string
                    example: transcript_id_here
                  blockDetails:
                    type: string
                    example: block_details_here
        '400':
          description: Bad request

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Admin:
      type: object
      properties:
        admin_id:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string

    Student:
      type: object
      properties:
        student_id:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        dob:
          type: string
          format: date
        address:
          type: string
        phone_number:
          type: string
        enrollment_year:
          type: string
        course:
          type: string
        semesters:
          type: array
          items:
            $ref: '#/components/schemas/Semester'

    Semester:
      type: object
      properties:
        semester_number:
          type: integer
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Subject'

    Subject:
      type: object
      properties:
        subject_name:
          type: string
        marks:
          type: number
        grade:
          type: string

    Transcript:
      type: object
      properties:
        transcript_id:
          type: string
        student_id:
          type: string
        details:
          type: string
        block_details:
          type: string
